import type { Copy } from "./types";

export const zh: Copy = {
  hero: {
    title: "先读懂代码，\n再开口的代码审查。",
    subtitle:
      "ocra 把一次改动拆成几个聚焦的审查任务。每个 agent 只能读你的仓库，必须引用它说的那段代码，并被要求交代自己查过什么。多数运行只报一两条意见，不少运行一条也没有，这也是正常结果。",
    start: "快速上手",
    github: "在 GitHub 查看源码",
    note: "Node 22+，支持 OpenCode 能用的任何模型",
  },
  run: {
    title: "运行 {command}\n时发生了什么",
    body: "不能出错的步骤，都是普通的、有测试的代码。只有需要判断的地方才交给模型。",
    legend: { code: "代码", model: "模型" },
    region: "一次审查的各个阶段",
    previous: "上一组阶段",
    next: "下一组阶段",
    example: "示例运行",
    demo: {
      label: "ocra review 示例运行的视频",
      caption:
        "一次示例运行，加速播放。流水线、输出和结论都来自 ocra 本身；模型的回答是为录制预先写好的。",
      play: "播放示例运行",
      pause: "暂停示例运行",
    },
    groups: [
      {
        title: "只读值得读的文件",
        stages: [
          { name: "select", kind: "code" },
          { name: "triage", kind: "code" },
        ],
        text: "二进制、锁文件、第三方和生成的代码、媒体文件、疑似密钥和过大的 diff 会被放到一边，每个都记录原因。涉及 auth/、CI workflow 这类敏感路径，或超过 20 个文件，直接定为 full 档；否则按改动量分为 trivial、lite 或 full。",
      },
      {
        title: "每组、每个审查员一个任务",
        stages: [
          { name: "bundle", kind: "model" },
          { name: "matrix", kind: "code" },
        ],
        text: "四个文件起，由轻量模型把该一起看的文件分成组；文件更少时用代码直接拆分。correctness 总会运行；security 和 performance 从 lite 档开始加入，并跳过文档和测试。被跳过的组合连同原因记录下来，--plan 能在调用模型之前列出全部任务。",
      },
      {
        title: "每条意见都引用它说的代码",
        stages: [
          { name: "review", kind: "model" },
          { name: "anchor", kind: "code" },
        ],
        text: "每组每个审查员一个隔离的 agent，用只读工具读取被审查的那个版本，最多执行 20 步，用引用代码的方式报告问题。ocra 先在 diff 里、再在整个文件里查找这段引用，定位到具体行；找不到时，这条意见只挂在文件上。行号从来不由模型决定。",
      },
      {
        title: "只留下经得起重读的意见",
        stages: [
          { name: "filter", kind: "code" },
          { name: "verify", kind: "model" },
          { name: "judge", kind: "model" },
          { name: "verdict", kind: "code" },
        ],
        text: "团队已经记入 ocra 记忆的问题，在花钱让模型核查之前就被去掉。核查模型把每条问题和代码放在一起重读，去掉被代码证伪的；Judge 合并同一根因、去掉吹毛求疵的意见，但不能去掉或降级已确认的 critical。结论由代码计算：只有经核查确认的 critical 才能拦下改动。",
      },
    ],
    figures: {
      read: "读取",
      lockSetAside: "放到一边：generated",
      tier: "档位",
      touches: "涉及 auth/",
      authCode: "auth 代码",
      docs: "文档",
      threeFiles: "3 个文件",
      oneFile: "1 个文件",
      skip: "跳过",
      tasks: "4 个审查任务",
      skipped: "跳过 2 个：没有匹配的文件",
      agent: "agent",
      on: "开",
      off: "关",
      quote: "引用",
      matched: "在 diff 里匹配到",
      confirmed: "已确认",
      merged: "并入 #1",
      disproved: "被证伪",
      accepted: "已被记忆接受",
      verdict: "结论：significant concerns",
      verifiedCritical: "1 条已核实的 critical",
    },
  },
  decisions: {
    title: "刻意做出的几个取舍",
    body: "每一条都有代价，我们认为值得。",
    items: [
      {
        title: "行号从来不由模型决定。",
        body: "模型不擅长行号，却很擅长引用。所以让它引用，由 ocra 去找行号。",
      },
      {
        title: "审查员被明确告知哪些别管。",
        body: "代码风格、没有依据的推测、没改动的代码，对每个审查员都不在范围内；每个审查员还有自己的排除清单，比如 correctness 不管缺少测试。一条都不报，也是合格的结果。",
      },
      {
        title: "agent 没有写权限。",
        body: "agent 能读文件、读 diff、在仓库里搜索。编辑、shell 和网络工具全部关闭，OpenCode 的其他内置工具也一并关闭。",
      },
      {
        title: "你自己的配置不进审查。",
        body: "在发出第一个请求之前，全局 OpenCode 配置、已安装的 skill 和指令文件都会被关掉，运行时也只拿到它需要的环境变量。",
      },
      {
        title: "每次尝试都有账单。",
        body: "每次审查尝试结束时，列出步数、工具调用、token 和花费；整次运行的合计还包括缓存 token 和每一次辅助调用。",
      },
      {
        title: "一个模型倒下，下一个接手。",
        body: "给每个层级配一串模型。遇到过载就换下一个；反复失败的模型会暂停一段时间，短暂限流会等待后重试，额度用尽的模型在本次运行里不再使用。",
      },
    ],
    visuals: {
      outOfScope: ["代码风格", "没有依据的推测", "没改动的代码", "缺少测试"],
      machine: ["OpenCode 全局配置", "已安装的 skill", "指令文件"],
      located: "定位到",
    },
  },
  anatomy: {
    title: "一条意见长什么样",
    body: "PR 上的一条行内评论，信息刚好够你在几秒内决定修还是忽略。之后怎么处理，取决于代码和审查者。",
    example: "示例 PR",
    callouts: {
      quote: "agent 引用的那一行，由 ocra 在 diff 里定位",
      lines: "严重程度、是否经过核查确认，以及是哪个审查员发现的",
      verified: "用平实的话说明错在哪里",
      suggestion: "有必要时，最小的修复",
    },
    states: {
      reported: {
        tab: "已报告",
        text: "下一次 push 时，只要这段代码没变，这条问题就保持打开，即使没有审查员再报一次。同样的代码，结论不会变。",
      },
      fixed: {
        tab: "已修复",
        text: "问题指向的那段代码已经不在文件里，ocra 会自己关闭这个讨论串。这是它认定已修复的唯一依据。",
        resolved: "github-actions 关闭了这个讨论",
      },
      dismissed: {
        tab: "已驳回",
        text: "维护者拒绝了这条问题。ocra 不再报告它，它也不再计入结论，除非它以更高的严重程度再次出现。PR 作者本人不能这样做。",
        reply: "Won't fix：这次 PR 先不改，已记录在 #812。",
        resolved: "维护者关闭了这个讨论",
        who: "维护者",
      },
    },
  },
  plugins: {
    title: "把团队规范写成插件",
    body: "Git 和 GitHub 适配器、OpenCode 运行时，以及目前自带的五个审查员，本身也是插件。你写的插件用的是同一套接口：注册规则、审查员、工具或事件监听，并拿到只属于自己的设置。插件会执行代码，所以只在本地审查时加载；审查 PR 时，同样的规则写在 base 分支的 .ocra/rules.json 里。",
    points: [
      "三个生命周期钩子，按固定顺序执行",
      "每个插件的设置单独校验",
      "注册冲突或越界注册时报错，并指出是哪个插件",
    ],
    cta: "阅读插件指南",
  },
  status: {
    title: "目前进展",
    window: "ocra — 路线图",
    items: [
      {
        milestone: "M1",
        title: "本地审查",
        body: "CLI、文件选择、分组、行号定位、correctness 审查员、OpenCode 运行时、插件、评测工具。",
        state: "已完成",
        done: true,
      },
      {
        milestone: "M2",
        title: "更多审查员",
        body: "安全与性能审查员、风险档位、审查矩阵、逐条核查、最终裁决，以及固定的结论规则。",
        state: "已完成",
        done: true,
      },
      {
        milestone: "M3",
        title: "GitHub",
        body: "ocra review --pr 和 GitHub Action：行内评论、一条摘要评论；之后的 push 只复审改动过的部分，自动关闭已修复的评论串，并尊重人工驳回。目前在模拟的 GitHub API 上测试过，第一次真实 PR 运行放在 M7。",
        state: "已完成",
        done: true,
      },
      {
        milestone: "M4",
        title: "加固",
        body: "每个模型的熔断器、通过 https 共享的配置、审查记忆，以及追求召回率的 --ultra 模式。",
        state: "已完成",
        done: true,
      },
      {
        milestone: "M5",
        title: "度量",
        body: "一套标注了预期问题的黄金集，加上 AACR-Bench。第一批结果已经连同局限一起公开：样本小，只测了一个模型家族，召回率是短板。把黄金集扩大到足以判断一次改动的规模，要等模型额度。",
        state: "已完成",
        done: true,
        link: { label: "查看结果", href: "/docs/quality" },
      },
      {
        milestone: "M6",
        title: "召回率",
        body: "审查员报告所有能拿出证据的问题，由核查和 Judge 负责准确率；每次只改一处提示词，并逐一度量。在有模型额度逐一度量之前暂停。",
        state: "暂停",
        done: false,
      },
      {
        milestone: "M7",
        title: "发布 v0.1",
        body: "v0.1 已带 provenance 发布到 npm，一行命令就能安装。Action 已在两个仓库的真实 PR 上审查。",
        state: "已完成",
        done: true,
      },
      {
        milestone: "M8",
        title: "不可信的 PR",
        body: "一份威胁模型、一套为来自 fork 的 PR 设置门槛的工作流，以及一组对抗测试：在被审查的改动里埋入指令、链接和命令。",
        state: "已完成",
        done: true,
        link: { label: "阅读威胁模型", href: "/docs/threat-model" },
      },
      {
        milestone: "M9",
        title: "覆盖面与可信度",
        body: "GitLab Merge Request（GitLab.com 和自建实例）；用于代码扫描的 SARIF；容器镜像；你自己的 OpenAI 兼容模型端点；安全策略和一次安全审计。已随 0.2.0 发布；在真实 GitLab 实例上的验证仍待进行。",
        state: "已完成",
        done: true,
      },
      {
        milestone: "M10",
        title: "契约",
        body: "ocra 的长期定位是其他审查 agent 赖以构建的引擎，而不是又一个 bot。先把契约立起来：带 JSON Schema 的 Finding 规范；一个公开的 review() 入口，CLI 和其他人一样调用它；第二个 agent 运行时，连同证明它不写文件、不开 shell、不连网络的一致性测试；以及 SARIF 导入，让静态分析工具进入同一条流水线。",
        state: "下一步",
        done: false,
      },
      {
        milestone: "M11",
        title: "证据",
        body: "CI 里每夜一次真实模型测试；黄金集扩大到能看出五个百分点的变化；按审查员、按模型公布准确率和召回率。提示词只在这些数字之下解冻。需要一条常设的模型额度。",
        state: "计划中",
        done: false,
      },
      {
        milestone: "M12",
        title: "可运维",
        body: "被审查仓库无法覆盖的组织级策略；贯穿日志、评论和报告的 run id；运维团队可以采集的指标。",
        state: "计划中",
        done: false,
      },
      {
        milestone: "M13",
        title: "外部使用",
        body: "三个外部团队用上一个月，他们的驳回和回复进入黄金集。他们的需要决定第二年做什么：控制面、组织级记忆、更多平台。",
        state: "计划中",
        done: false,
      },
    ],
  },
  start: {
    title: "拿一个你熟悉的仓库试试",
    body: "它可以在你本机的任何 Git 仓库上运行，也可以通过 GitHub Action 审查 PR。模型供应商能看到的是：这次改动及其标题和描述、你的 AGENTS.md 和审查规则，以及 agent 在仓库里打开或搜索到的内容；看起来像密钥的文件和仓库以外的东西，它都看不到。",
    copy: "复制",
    copied: "已复制",
    copyFailed: "请手动选中复制",
    docs: "阅读快速上手",
    tabs: { cli: "本地 CLI", action: "GitHub Action" },
    actionNote:
      "保存为 .github/workflows/ocra.yml，并把模型 key 存为仓库 secret。模型写在 env 里，或写在 base 分支的 .ocra/config.json 里。之后每个 PR 都会收到行内评论和一条摘要。",
    actionDocs: "阅读 GitHub 指南",
  },
  footer: {
    tagline: "先读代码再下结论的开源代码审查。",
    github: "GitHub",
    license: "Apache-2.0",
    manual: "手册",
    wordmark: "ocra",
  },
};
